### PR TITLE
do not assume blame_field_specs is always there

### LINKED ISSUE #34: KeyError: 'blame_field_specs'
While creating adsets using batch

```
Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    execute_from_command_line(sys.argv)
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/web/work4us/python/sjp_app/management/commands/push_sjp_ads_campaign_csv.py", line 49, in handle
    adsets = self.create_adsets(campaign, adsets_data)
  File "/home/web/work4us/python/sjp_app/management/commands/push_sjp_ads_campaign_csv.py", line 74, in create_adsets
    batch.execute()
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/facebookads/api.py", line 439, in execute
    self._failure_callbacks[index](inner_fb_response)
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/facebookads/objects.py", line 500, in callback_failure
    failure(response)
  File "/home/web/work4us/python/ads_app/api/utils.py", line 24, in failure_default_batch_callback
    raise response.error()
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/facebookads/api.py", line 111, in error
    self.body()
  File "/home/web/work4us/venv/local/lib/python2.7/site-packages/facebookads/exceptions.py", line 75, in __init__
    self._error['error_data']['blame_field_specs']
KeyError: 'blame_field_specs'
```
the actual error was:
```
{u'error': {u'is_transient': False, u'error_subcode': 1487478, u'error_user_title': u'Invalid Geo Locations', u'error_data': {u'blame_field': u'targeting'}, u'error_user_msg': u'Invalid Geo Locations', u'code': 100, u'message': u'Invalid parameter', u'type': u'FacebookApiException'}}

### PR DESCRIPTION
**Pull request by m-vdb**
fixes #34

### CODE REVIEW

**Comment by ebzlo** [comment]
@m-vdb this looks good to me, i've pulled it internally so it can get reviewed and merged in

**Comment by m-vdb** [comment]
thanks !

**Comment by m-vdb** [comment]
@ebzlo any news ? :)

**Comment by ebzlo** [comment]
Hey @m-vdb! Sorry for the delay, I'll shoot to get this later tonight or tomorrow.

**Comment by m-vdb** [comment]
thanks you rock!

**Comment by m-vdb** [comment]
yay!

**Pull request merged**
