### PR TITLE
EdgeIterator.total() should raise if _total_count is None

### PR DESCRIPTION
**Pull request by m-vdb**
@ebzlo this PR is cleaner, with unit tests

### CODE REVIEW

**Comment by ebzlo** [comment]
Cool! Thanks for the cleanup. Could you actually raise and catch a different (new) Exception?

Create `FacebookUnavailablePropertyException` (or something to that effect) and raise it here.

**Comment by m-vdb** [comment]
yes of course!

**Comment by m-vdb** [comment]
done, when do you think you'll do a pip release of the SDK?

I also take the opportunity to tell you that we now run the integration tests on our own account, automatically. As a result, as we discover errors / bugs / unexpected behaviours, we'll contribute to strengthen your integrations tests :)

**Comment by ebzlo** [comment]
@m-vdb we have a broken test at the moment that is slated to be fixed early next week. We'll do a pip release then. :)

**Comment by ebzlo** [comment]
Pulling in for review, could you modify all lines to be less than 80 characters?

**Comment by m-vdb** [comment]
ah yes you have strict linter :) no problem

**Comment by m-vdb** [comment]
there you go, I can rebase if you want. Thanks for the release, will wait for it :)

**Comment by m-vdb** [comment]
@ebzlo any news?

**Comment by m-vdb** [comment]
@ebzlo gentle ping :)

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Pull request closed without merging**
