### PR TITLE
Repair try/except syntax for Python 3

### PR DESCRIPTION
**Pull request by agriffis**
This fixes the Travis failure, see https://travis-ci.org/facebook/facebook-python-ads-sdk/jobs/46396202

### CODE REVIEW

**Comment by ebzlo** [comment]
Thanks! There's already a diff out but waiting on approval. :(

Evan



On Jan 8, 2015, at 8:07 PM, Aron Griffis <notifications@github.com<mailto:notifications@github.com>> wrote:


This fixes the Travis failure, see https://travis-ci.org/facebook/facebook-python-ads-sdk/jobs/46396202<https://urldefense.proofpoint.com/v1/url?u=https://travis-ci.org/facebook/facebook-python-ads-sdk/jobs/46396202&k=ZVNjlDMF0FElm4dQtryO4A%3D%3D%0A&r=h1eSN7JIbTeTjOoCFln5mg%3D%3D%0A&m=mw5daeaS28Dc93UfyC0l4mnVS8UwY%2BjihaYjU0EJpvg%3D%0A&s=f0a4b8072bb109a2efc00c01868369238d604e26e4d4c320b1f768fbf7f3b1a8>

________________________________
You can merge this Pull Request by running

  git pull https://github.com/agriffis/facebook-python-ads-sdk except-py3

Or view, comment on, or merge it at:

  https://github.com/facebook/facebook-python-ads-sdk/pull/26

Commit Summary

  *   Repair try/except syntax for Python 3

File Changes

  *   M facebookads/test/unit.py<https://github.com/facebook/facebook-python-ads-sdk/pull/26/files#diff-0> (2)

Patch Links:

  *   https://github.com/facebook/facebook-python-ads-sdk/pull/26.patch
  *   https://github.com/facebook/facebook-python-ads-sdk/pull/26.diff

**Comment by agriffis** [comment]
Haven't switched internally from running `python -m facebookads.test.unit` to running `tox`? ;-)

**Comment by ebzlo** [comment]
@agriffis you got me :(

**Comment by ebzlo** [comment]
closing this, it will be coming in through a different update.

**Pull request closed without merging**
